sudo: required
dist: trusty
before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build cv.tex