
sudo: required
dist: trusty
before_install:
    - sudo apt-get update
    - sudo apt-get install -y texlive xzdec
    - tlmgr init-usertree
    - tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
    - sudo tlmgr install titlesec supertabular
script:
    - mkdir _build
    - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build cv.tex

notifications:
    email:
        on_success: change
        on_failure: always
